DROP TABLE IF EXISTS TBL_ACKNOWLEDGMENT_RECEIPT;
 
CREATE TABLE TBL_ACKNOWLEDGMENT_RECEIPT (
  ack_id INT AUTO_INCREMENT  PRIMARY KEY,
  transaccion_id VARCHAR(25) NOT NULL,
  code VARCHAR(25) NOT NULL,
	message VARCHAR(50),
	date VARCHAR(100)
);

DROP TABLE IF EXISTS TBL_DETAIL_ERROR;
 
CREATE TABLE TBL_DETAIL_ERROR (
  error_id INT AUTO_INCREMENT  PRIMARY KEY,
  ack_id INT NOT NULL,
	code VARCHAR(50) NOT NULL,
	message VARCHAR(250) NOT NULL,
	FOREIGN KEY (ack_id) REFERENCES TBL_ACKNOWLEDGMENT_RECEIPT(ack_id)
);


alter table TBL_DETAIL_ERROR add FOREIGN KEY (ack_id) REFERENCES TBL_ACKNOWLEDGMENT_RECEIPT(ack_id);
